### ISSUE TITLE
Issue while Training Mnist

### ISSUE THREAD

**Issue by Gnillor** [Intel-bigdata/CaffeOnYARN#2]
Issue while Training Mnist.

Error Message:

	at org.apache.hadoop.util.Shell.runCommand(Shell.java:976)
	at org.apache.hadoop.util.Shell.run(Shell.java:880)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1174)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:293)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.launchContainer(ContainerLaunch.java:425)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:285)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:88)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

    Container exited with a non-zero exit code 127. Last 4096 bytes of 
    Caffe.stderr :
    /bin/bash: @152c79b3: command not found

    Container exited with a non-zero exit code 127. Last 4096 bytes of 
    Caffe.stderr :
    /bin/bash: @152c79b3: command not found

**Comment by Gnillor** [comment]
fixed in #3
